## Fill in data in the following format :
#Vgg16:
#  version:
#  dependents:
#    Pytorch: [1.1, 2.2, 3.3]
#    Numpy: [1.1, 2.2]
#    Opencv: [1.0]
#  test_method: [FGSM, PGD, CW, DeepFool]
#  download_addr: xxxx/path
#  docker_container: xxx

Vgg16:
  version:
  dependents:
    Pytorch: 2.2
    Numpy: 1.1
    Opencv: 1.0
  test_method: [FGSM, PGD, CW, DeepFool]
  weight_number: 3
  weight_name: [name1, name2, name3]
  download_addr: xxxx/path1
  docker_container: xxx
  adver_metrics: ["ACC", "ACTC", "ASS"]

Vgg19:
  version:
  dependents:
    Pytorch: 2.2
    Numpy: 1.1
    Opencv: 1.0
  test_method: [FGSM, PGD, CW, DeepFool]
  weight_number: 3
  weight_name: [name1, name2, name3]
  download_addr: xxxx/path
  docker_container: xxx
  adver_metrics: ["ACC", "ACTC", "ASS"]

Librispeech:
  version:
  dependents:
    Pytorch: 2.2
    Numpy: 1.1
    Opencv: 1.0
  test_method: [FGSM, PGD, CW, DeepFool]
  weight_number: 3
  weight_name: [name1, name2, name3]
  download_addr: xxxx/path
  docker_container: xxx
  adver_metrics: ["ACC", "ACTC", "ASS"]